blank_issues_enabled: false
contact_links:
  - name: Raider Aerospace Society Avionics Teams
    url: https://teams.microsoft.com/ # replace with real link if desired
    about: For general questions/discussions, use the Teams channel instead of creating an issue.
