name: Feature request
description: Suggest a new feature or improvement
title: "[FEAT] <short summary>"
labels: ["type:feature", "needs-triage"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One or two sentences describing the feature
      placeholder: "Add servo boot sequence on power-up"
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What’s included (and explicitly what’s not)?
      placeholder: |
        - Init servo at boot
        - Closed→open→closed motion
        - Update boot logs
        Not in scope: PID tuning
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Objective checks that prove “done”
      placeholder: |
        - pio run passes
        - Boot log shows motion sequence
        - Docs updated
    validations:
      required: true

  - type: dropdown
    id: subsystem
    attributes:
      label: Subsystem
      options:
        - Firmware
        - Hardware
        - Docs
        - CI
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 (urgent/blocking)
        - P1 (important)
        - P2 (nice to have)
