name: Research task
description: Use for investigation or option comparisons
title: "[RES] <short summary>"
labels: ["type:research", "needs-triage"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question / Problem
      description: What are we trying to learn or decide?
      placeholder: "Compare pan/tilt options for antenna tracking"
    validations:
      required: true

  - type: textarea
    id: approach
    attributes:
      label: Approach
      description: How will you research this? (read datasheets, test hardware, etc.)
      placeholder: "Survey available servo models, test torque requirements..."

  - type: textarea
    id: deliverable
    attributes:
      label: Deliverable
      description: What output should exist when this issue is done?
      placeholder: "Markdown doc in /docs/research/pan_tilt.md summarizing findings"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 (urgent/blocking)
        - P1 (important)
        - P2 (nice to have)
